### ISSUE TITLE
Add contact page

### ISSUE THREAD

**Issue by dvzrv** [linuxaudio/lac2018#5]
Add page to list ways to contact the planning team.
Mail and IRC. Anything else?

**Comment by x42** [comment]
Don't forget a travel&stay page related to this.

compare to http://lac.linuxaudio.org/2015/travel  and  http://lac.linuxaudio.org/2014/travel

**Comment by dvzrv** [comment]
Different issue!
I'd rather go for: http://minilac.linuxaudio.org/index.php/C-base#Staying_around and http://minilac.linuxaudio.org/index.php/C-base#Getting_there

**Comment by dvzrv** [comment]
Added with https://github.com/linuxaudio/lac2018/commit/7d305d2e488dd33bdfb4314263d506cb7a2c8d9b
