### ISSUE TITLE
Add travel and stay page

### ISSUE THREAD

**Issue by dvzrv** [linuxaudio/lac2018#6]
Add a page listing travel and stay information:

http://minilac.linuxaudio.org/index.php/C-base#Getting_there
http://minilac.linuxaudio.org/index.php/C-base#Staying_around

**Comment by ri0t** [comment]
Integrated. Please verify.

**Comment by dvzrv** [comment]
Thanks! :)
Next time please use `nikola new_page` to have the header in the file, where you can easily set the page slug.
